AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
<<<<<<< HEAD
      Runtime: python 3.8.2
      CodeUri: F:\AWS\PipeLine\LambdaCDDemo-master\LambdaCode
=======
      Runtime: python3.8.2
      CodeUri: ./PipeLine/LambdaCDDemo-master/LambdaCode
>>>>>>> 9b2d93bdcadeca0929895740d9012e713cddedf0
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::393583232489:role/CloudFormationServiceRole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-2